name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine

    - name: Run build
      uses: cedrickring/golang-action@1.6.0
      with:
        args: make build

    - name: Run build
      uses: cedrickring/golang-action@1.6.0
      with:
        args: make test
